services:
  hms_debug:
    build: .
    container_name: hms_debug
    command: flask run --host=0.0.0.0 --port=5000 --debug
    ports:
      - "5000:5000"
      - "5678:5678"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
    volumes:
      - .:/app # Mount local project files to container

  hms_prod:
    image: priyankanetweb/hms-2:0.0.1.RELEASE
    container_name: hms_prod
    command: gunicorn --bind 0.0.0.0:5001 app:app
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hms_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
