"""Added available_slots column to Doctor table

Revision ID: 0906aa28d4ae
Revises: 
Create Date: 2025-02-06 13:07:13.217605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0906aa28d4ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_slots', sa.String(length=100), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['id'], ['id'])

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('available_slots')

    # ### end Alembic commands ###
